theme: jekyll-theme-minimal
title: Caitlin Cabrera
description: Independent Study Summer 2020  CIRDLES Lab
paginate_path: /posts/
plugins: [jekyll-paginate]
logo: https://avatars1.githubusercontent.com/u/46205451?s=460&u=b50542bb3a80cfebca068cd1148d556e1bc8e86c&v=4


